version: '3.7'

services:
  app:
    image: gym-tracker-server
    ports:
      - 3000:3000
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GO_ENV=${GO_ENV}
      - GIN_MODE=${GIN_MODE}
    