services:
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    container_name: gymTrackerDB
    volumes:
      - gym-tracker-db:/var/lib/postgresql/data

volumes:
  gym-tracker-db: